# Generated by Django 4.2.3 on 2023-09-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_discription',
            new_name='todo_description',
        ),
    ]
